name: "Java Build Action"
description: "Compile and run Java program"

inputs:
  file-name:
    description: "Java file name"
    required: true

  username:
    required: true
    description: "User name"

outputs:
  result:
    description: "Build result"

  message:
    description: "Greeting message"


runs:
  using: "composite"

  steps:
    - name: Compile Java Program
      run: javac *.java
      shell: bash

    - name: Run Java Program
      run: java ${{inputs.file-name}}
      shell: bash

    - name: Run Test
      run: java CalculatorTest
      shell: bash

    - name: Set Output
      run: echo "result=Build Successful" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create Greeting
      run: echo "message=Hello ${{inputs.username}}" >> $GITHUB_OUTPUT
      shell: bash