name: "Java Build Action"
description: "Compile and run Java program"

inputs:
  file-name:
    description: "Java file name"
    required: true
runs:
  using: "composite"

  steps:
    - name: Compile Java Program
      run: javac ${{inputs.file-name}}.java
      shell: bash

    - name: Run Java Program
      run: java ${{inputs.file-name}}
      shell: bash

    - name: Run Test
      run: java CalculatorTest
      shell: bash