name: Java CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Custom Action
        uses: ./.github/actions/java-build
        with:
          file-name: Main

      - name: Run Custom Action
        id: custom-action
        uses: ./.github/actions/java-build

      - name: Print Output
        run: echo "${{ steps.java-build.outputs.result }}"

      - name: Run Greeting Action
        id: greet-action
        uses: ./.github/actions/java-build
        with:
          username: Pasindu

      - name: Show Greeting
        run: echo "${{ steps.greet-action.outputs.result }}"